import Head from "next/head";
import Post from "../components/Post/Post";
import PostForm from "../components/PostForm";
import styles from "../styles/Home.module.scss";
import Bio from '../components/Bio/Bio';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <main className={styles.main}>
          <Bio
            headshot="https://media-exp2.licdn.com/dms/image/C4D03AQEPaCAHLkI8FQ/profile-displayphoto-shrink_800_800/0/1653202681957?e=1662595200&v=beta&t=oE8RSbJ07Q1ksngOC17DxESG266xQBS3ptaWYvNKcdQ"
            name="Akil Varlı"
            tagline="Helping Others learn by doing!"
            role="Developer Advocate @ Applitools"
          />
          <ul className={styles.posts}>
            <li>
              <Post content="Hey, I'm a new post!" date="1/7/2022" />
            </li>
            <li>
              <Post
                content="I'm working in Figma trying to design a new website that shows all of my tweets!"
                date="2/7/2022"
              />
            </li>
            <li>
              <Post
                content="I'm working in Figma trying to design a new website that shows all of my tweets!"
                date="3/7/2022"
              />
            </li>
            <li>
              <Post
                content="I'm working in Figma trying to design a new website that shows all of my tweets!"
                date="3/7/2022"
              />
            </li>
          </ul>
          <PostForm />
        </main>
      </div>
    </div>
  );
}
